"metafile_paths" = ["/opt/code/python-ismrmrd-server/seq_meta"]
"girf_file" = "GIRF/GIRF_20200221_Duyn_method_coil2.mat"

[reconstruction]
"apply_girf"        = true
"arms_per_frame"    = 55
"window_shift"      = 17
"gpu_device"        = 0
"coil_combine"      = "rssq" # Options: "rssq", "adaptive"
"save_complex"      = false # Save complex float images, rather than scaled magnitude int images.
"ignore_arms_per_frame" = false # When true, arms per frame and window shift are ignored and arms to grid will be interleaves parameter in the metadata. Useful for linear ordering.
