name: ci

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
    tags:
      - 'v*.*.*'

jobs:
  build_devcontainer:
      runs-on: ubuntu-latest
      steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: docker.io/kspacekelvin/fire-python-devcon
          cacheFrom: docker.io/kspacekelvin/fire-python-devcon
          push: always
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Make GitHub branch name compatible with Docker tags
        id: extract_branch
        run: |
          FULL_BRANCH=${GITHUB_REF#refs/heads/}
          SAFE_BRANCH=${FULL_BRANCH//\//-}
          echo "SAFE_BRANCH=${SAFE_BRANCH}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          cache-from: type=registry,ref=kspacekelvin/fire-python:buildcache
          cache-to: type=registry,ref=kspacekelvin/fire-python:buildcache,mode=max
          push: true
          tags: |
            kspacekelvin/fire-python:latest
            kspacekelvin/fire-python:${{ env.SAFE_BRANCH }}